name: DEPLOY
on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: rsync deployments
      uses: burnett01/rsync-deployments@5.2
      with:
        switches: -tuvr
        path: /
        remote_path: /home/cum/htdocs/cum.fi/
        remote_host: vps-fi-hel1.domsku.com
        remote_port: ${{ secrets.SSH_PORT }}
        remote_user: cum
        remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
